### ISSUE TITLE
Rerouting markers on map should instead show a list of options to choose from

### ISSUE THREAD

**Issue by CloudNiner** [azavea/nih-wayfinding#102]
@jfrankl I believe there was mention of wireframe work on this, but we will get started on it, and use the directions list view as a template.

**Comment by CloudNiner** [comment]
Also, sort options by distance ascending

**Comment by jfrankl** [comment]
That sounds like a good starting place. Thanks Andrew.

On Wed, Feb 4, 2015 at 4:52 PM, Andrew Fink notifications@github.com
wrote:

> Also, sort options by distance ascending
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/azavea/nih-wayfinding/issues/102#issuecomment-72947494
> .

## 

Jeff Frankl, UI/UX Designer

Azavea  |  340 N 12th St, Suite 402, Philadelphia, PA
Web azavea.com  |  Blog azavea.com/blogs  |  Twitter @azavea
http://twitter.com

**Comment by CloudNiner** [comment]
Closing, superseded by #110
