### ISSUE TITLE
Add a class when notifications bar is visible instead of animating on height

### ISSUE THREAD

**Issue by jfrankl** [azavea/nih-wayfinding#105]

**Comment by CloudNiner** [comment]
Are you referring to the notifications bar rather than the navigation bar?

**Comment by jfrankl** [comment]
Good catch. Yes, I meant notifications bar.

On Fri, Feb 6, 2015 at 3:13 PM, Andrew Fink notifications@github.com
wrote:

> Are you referring to the notifications bar rather than the navigation bar?
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/azavea/nih-wayfinding/issues/105#issuecomment-73304481
> .

## 

Jeff Frankl, UI/UX Designer

Azavea  |  340 N 12th St, Suite 402, Philadelphia, PA
Web azavea.com  |  Blog azavea.com/blogs  |  Twitter @azavea
http://twitter.com
