### ISSUE TITLE
Use icons instead of text for turn by turn view

### ISSUE THREAD

**Issue by jfrankl** [azavea/nih-wayfinding#109]
Text can be used as alt text.

There should be icons for:
- Bench
- Tree cover (greater than 50%)
- Retail
- Beauty
- Something bad (even if there are multiple, should only show one icon)

![image](https://cloud.githubusercontent.com/assets/1809908/6068713/60f22412-ad4c-11e4-808d-a2c44b2930d6.png)

**Comment by flibbertigibbet** [comment]
I'm pretty sure we don't have data yet on tree coverage.  We also don't have data for shopping associated with streets in the directions coming back (if somebody searches for shopping places for potential destinations, that's totally separate from the routing graph).

**Comment by jbranigan** [comment]
I'm working on tree coverage, aesthetics, and retail density. It'll be ready for the next sprint.
