### ISSUE TITLE
Move direction text from header to sub-header space

### ISSUE THREAD

**Issue by jfrankl** [azavea/nih-wayfinding#111]
You know what to do, Jeff.

![image](https://cloud.githubusercontent.com/assets/1809908/6068800/09d97cba-ad4d-11e4-9c90-07e109a4922a.png)

**Comment by flibbertigibbet** [comment]
I'm pretty sure we don't have anything in place yet for finding landmark names to display in turn directions.

**Comment by jbranigan** [comment]
Wasn't this supposed to do that?
https://github.com/azavea/nih-wayfinding/pull/37

**Comment by flibbertigibbet** [comment]
Ah, ok.  I haven't seen any listed in the directions I've gotten yet.

**Comment by jbranigan** [comment]
It might not be hooked up yet.

**Comment by CloudNiner** [comment]
See turn-amenities.js, @sharph wrote that code I believe. The turn amenities helper should attach in Directions.get handler after the OTP json is transformed. I believe the location name was only wired up to display in the directions list view?

**Comment by flibbertigibbet** [comment]
Yes, looks like it's wired in; I've just never noticed it actually show a response.
