### ISSUE TITLE
oracle jdk

### ISSUE THREAD

**Issue by moradology** [azavea/nih-wayfinding#60]
If we so desire, we can use the JRE that OTP supports:
https://github.com/agileorbit-cookbooks/java#oracle

**Comment by flibbertigibbet** [comment]
What we've got requires 7; it's not going to compile on 6 any more.  Don't see any reason to use an older version, anyway.

**Comment by moradology** [comment]
I assumed we'd use 7 - I think Oracle has version 7 out too. In fact, I think openJDK just follows Oracle's spec. @hectcastro probably knows the specifics.

**Comment by flibbertigibbet** [comment]
I'd prefer if we were using Oracle 7, yes.  I think we should be able to just use the [webup8 PPA](https://launchpad.net/~webupd8team/+archive/ubuntu/java).

**Comment by CloudNiner** [comment]
The easiest way to get the oracle jdk is going to be the webupd8 ppa. There is a flag you can set before install to automatically agree to the licensing terms.
