### ISSUE TITLE
Current location circle disappears from navigation view

### ISSUE THREAD

**Issue by CloudNiner** [azavea/nih-wayfinding#73]
Reproduce by navigating away from the navigate view and then back to it.

**Comment by flibbertigibbet** [comment]
Also, the navigation linestring disappears if user navigates to directions list, then back to map.

**Comment by CloudNiner** [comment]
I can no longer reproduce this. Closing.

**Comment by moradology** [comment]
Pretty sure this was fixed in PR #80
