### ISSUE TITLE
Move geolocation point closer to audited streets

### ISSUE THREAD

**Issue by CloudNiner** [azavea/nih-wayfinding#95]

**Comment by jbranigan** [comment]
3240 East 91st Street would be good

**Comment by jbranigan** [comment]
-87.54867,41.73045 is maybe a bit more accurate on my part. This puts us within the audited segments.

**Comment by CloudNiner** [comment]
@jbranigan it looks like a segment always returns from OTP as unverified if we only route along a very small piece of it. @flibbertigibbet is looking into the OTP side of things
